"""
Basic Dialectics Examples
Simple, educational examples demonstrating the core concepts of Xenopoulos' Fourth Logical Structure

These examples are designed to be:
1. Easy to understand for beginners
2. Self-contained with minimal dependencies  
3. Educational with clear explanations
4. Demonstrating core Hegelian dialectics with INRC operators
"""

import numpy as np
import matplotlib.pyplot as plt
from typing import List, Dict, Any
import sys
import os

# Add parent directory to path to import our package
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

try:
    from xenopoulos import DialecticalFactory, SynthesisMethod
    print("✅ Imported Xenopoulos package successfully")
except ImportError:
    print("⚠️  Could not import Xenopoulos package. Using simplified implementations.")
    
    # Simplified implementations for educational purposes
    class DialecticalFactory:
        @staticmethod
        def create_default_service():
            return SimpleDialecticalService()
    
    class SimpleDialecticalService:
        def create_dialectical_process(self, thesis, name=None):
            return SimpleDialecticalProcess(thesis, name)
    
    class SimpleDialecticalProcess:
        def __init__(self, thesis, name):
            self.thesis = thesis
            self.name = name or f"Process_{hash(tuple(thesis)) % 1000}"
            self.states = [{'thesis': thesis, 'antithesis': [-x for x in thesis]}]
        
        def run_cycle(self):
            current = self.states[-1]
            new_thesis = current['antithesis']
            self.states.append({
                'thesis': new_thesis,
                'antithesis': [-x for x in new_thesis]
            })
            return self.states[-1]

# ============================================================================
# 1. BASIC CONCEPT DEMONSTRATIONS
# ============================================================================

def demonstrate_basic_concepts():
    """
    Demonstrate the basic concepts of dialectics and INRC operators
    """
    print("\n" + "="*70)
    print("1. BASIC CONCEPTS OF XENOPOULOS' FOURTH LOGICAL STRUCTURE")
    print("="*70)
    
    # Create a simple dialectical service
    factory = DialecticalFactory()
    service = factory.create_default_service()
    
    # Example 1: Simple thesis-antithesis
    print("\n📚 Example 1: Thesis and Antithesis")
    print("-"*50)
    
    thesis = [1.0, 0.5, -0.3]
    print(f"Thesis: {thesis}")
    print(f"   Represents an initial position or idea")
    
    antithesis = [-x for x in thesis]
    print(f"Antithesis: {antithesis}")
    print(f"   The negation or opposite of the thesis")
    print(f"   Generated by N operator: N(x) = -x")
    
    # Example 2: INRC operators
    print("\n📚 Example 2: INRC Operators")
    print("-"*50)
    
    vector = [1, 2, 3]
    print(f"Vector: {vector}")
    
    # Simulate operators
    I = vector  # Identity
    N = [-x for x in vector]  # Negation
    R = list(reversed(vector))  # Reciprocity (order reversal)
    C = [-x for x in R]  # Correlation
    
    print(f"I (Identity): {I}        → I(x) = x")
    print(f"N (Negation): {N}     → N(x) = -x")
    print(f"R (Reciprocity): {R}        → R(x₁,x₂,x₃) = (x₃,x₂,x₁)")
    print(f"C (Correlation): {C}     → C = N∘R = R∘N")
    
    # Example 3: Klein-4 group properties
    print("\n📚 Example 3: Klein-4 Group Properties")
    print("-"*50)
    
    print("The INRC operators form a Klein-4 group (ℤ₂ × ℤ₂):")
    print("• All operators are self-inverse: a² = I")
    print("  Example: N(N(x)) = -(-x) = x = I(x)")
    print("• Commutative: a∘b = b∘a")
    print("  Example: N∘R = R∘N = C")
    print("• Specific relations:")
    print("  N∘R = C, R∘N = C")
    print("  R∘C = N, C∘R = N")
    print("  N∘C = R, C∘N = R")
    
    # Example 4: Critical correction
    print("\n📚 Example 4: Mathematical Correction")
    print("-"*50)
    
    print("⚠️  IMPORTANT: Common implementation error corrected")
    print("Wrong: R as cyclic permutation: R[i, (i+1)%n] = 1")
    print("       This only works for n=2, fails for n>2")
    print("Correct: R as order reversal: R[i, n-1-i] = 1")
    print("         Works for ALL n ≥ 2, ensures R² = I")
    
    # Demonstrate with n=3
    print("\nDemonstration with n=3:")
    v = [1, 2, 3]
    R_correct = list(reversed(v))  # [3, 2, 1]
    R_wrong = [v[1], v[2], v[0]]   # [2, 3, 1] - cyclic
    
    print(f"Vector: {v}")
    print(f"Correct R (order reversal): {R_correct}")
    print(f"Wrong R (cyclic): {R_wrong}")
    print(f"R_correct(R_correct(v)) = {list(reversed(R_correct))} = v ✓")
    print(f"R_wrong(R_wrong(v)) = {[R_wrong[1], R_wrong[2], R_wrong[0]]} ≠ v ✗")

# ============================================================================
# 2. SIMPLE DIALECTICAL PROCESSES
# ============================================================================

def demonstrate_simple_dialectics():
    """
    Demonstrate simple dialectical processes
    """
    print("\n" + "="*70)
    print("2. SIMPLE DIALECTICAL PROCESSES")
    print("="*70)
    
    factory = DialecticalFactory()
    service = factory.create_default_service()
    
    # Example 1: Binary opposition
    print("\n📚 Example 1: Binary Opposition (True/False)")
    print("-"*50)
    
    # Create process representing a binary debate
    thesis = [1.0]  # "True" or "Yes"
    process_id = service.create_dialectical_process(
        thesis=thesis,
        name="Binary Debate: True vs False"
    )
    
    print(f"Thesis: {thesis} (representing 'True')")
    print(f"Antithesis: {[-x for x in thesis]} (representing 'False')")
    print("\nHegelian dialectical process:")
    print("1. Thesis: Initial position ('True')")
    print("2. Antithesis: Negation ('False')")
    print("3. Synthesis: Resolution ('Maybe both have truth')")
    print("4. Negation of Negation: New thesis emerges")
    
    # Example 2: Political spectrum
    print("\n📚 Example 2: Political Spectrum (Left vs Right)")
    print("-"*50)
    
    # Represent political positions on multiple axes
    # [economic, social, environmental]
    left_position = [0.8, 0.9, 0.7]   # Progressive, egalitarian, environmental
    right_position = [-0.8, -0.6, -0.3] # Conservative, traditional, market-based
    
    print("Left position (thesis):")
    print(f"  Economic: {left_position[0]:+.2f} (egalitarian)")
    print(f"  Social: {left_position[1]:+.2f} (progressive)")
    print(f"  Environmental: {left_position[2]:+.2f} (protection)")
    
    print("\nRight position (antithesis):")
    print(f"  Economic: {right_position[0]:+.2f} (market-based)")
    print(f"  Social: {right_position[1]:+.2f} (traditional)")
    print(f"  Environmental: {right_position[2]:+.2f} (balanced)")
    
    print("\nDialectical synthesis might find:")
    print("• Market mechanisms with social safety nets")
    print("• Progressive values respecting tradition")
    print("• Sustainable development")
    
    # Example 3: Scientific theory development
    print("\n📚 Example 3: Scientific Theory Development")
    print("-"*50)
    
    # Represent competing scientific theories
    old_theory = [0.9, 0.8, 0.7]    # Established theory
    new_evidence = [-0.6, 0.3, -0.8] # Challenging evidence
    
    print("Established theory (thesis):")
    print("  Well-supported by existing evidence")
    print("  Consistent with current paradigm")
    
    print("\nNew evidence (antithesis):")
    print("  Contradicts some predictions")
    print("  Suggests need for revision")
    
    print("\nScientific dialectic:")
    print("1. Thesis: Established theory")
    print("2. Antithesis: Contradictory evidence")
    print("3. Synthesis: Revised theory")
    print("4. New thesis: Improved understanding")
    
    # Example 4: Personal decision making
    print("\n📚 Example 4: Personal Decision Making")
    print("-"*50)
    
    # Decision factors: [logic, emotion, practicality, ethics]
    rational_choice = [0.9, 0.2, 0.8, 0.7]   # Logical, practical
    emotional_choice = [0.3, 0.9, 0.4, 0.6]  # Emotional, ethical
    
    print("Rational approach (thesis):")
    print(f"  Logic: {rational_choice[0]:.1f}, Emotion: {rational_choice[1]:.1f}")
    print(f"  Practicality: {rational_choice[2]:.1f}, Ethics: {rational_choice[3]:.1f}")
    
    print("\nEmotional approach (antithesis):")
    print(f"  Logic: {emotional_choice[0]:.1f}, Emotion: {emotional_choice[1]:.1f}")
    print(f"  Practicality: {emotional_choice[2]:.1f}, Ethics: {emotional_choice[3]:.1f}")
    
    print("\nWise decision (synthesis):")
    print("  Balances logic and emotion")
    print("  Considers both practicality and ethics")
    print("  Emerges from considering both perspectives")

# ============================================================================
# 3. VISUAL DEMONSTRATIONS
# ============================================================================

def visualize_dialectical_process():
    """
    Visualize a dialectical process
    """
    print("\n" + "="*70)
    print("3. VISUALIZING DIALECTICAL PROCESSES")
    print("="*70)
    
    try:
        import matplotlib.pyplot as plt
        import numpy as np
        
        # Simple 2D example for visualization
        thesis = np.array([1.0, 0.5])
        antithesis = np.array([-0.8, 0.7])
        
        # Calculate synthesis (simple average for visualization)
        synthesis = (thesis + antithesis) / 2
        negation_of_negation = -synthesis
        
        # Create plot
        fig, ax = plt.subplots(1, 2, figsize=(12, 5))
        
        # Plot 1: Vector positions
        ax[0].quiver(0, 0, thesis[0], thesis[1], angles='xy', scale_units='xy', scale=1, 
                    color='blue', width=0.01, label='Thesis')
        ax[0].quiver(0, 0, antithesis[0], antithesis[1], angles='xy', scale_units='xy', scale=1,
                    color='red', width=0.01, label='Antithesis')
        ax[0].quiver(0, 0, synthesis[0], synthesis[1], angles='xy', scale_units='xy', scale=1,
                    color='green', width=0.01, label='Synthesis')
        ax[0].quiver(0, 0, negation_of_negation[0], negation_of_negation[1], angles='xy', scale_units='xy', scale=1,
                    color='purple', width=0.01, label='Negation of Negation')
        
        ax[0].set_xlim(-1.5, 1.5)
        ax[0].set_ylim(-1.5, 1.5)
        ax[0].grid(True, alpha=0.3)
        ax[0].axhline(y=0, color='k', alpha=0.3)
        ax[0].axvline(x=0, color='k', alpha=0.3)
        ax[0].set_aspect('equal')
        ax[0].set_title('Dialectical Process in 2D Space')
        ax[0].legend()
        ax[0].set_xlabel('Dimension 1')
        ax[0].set_ylabel('Dimension 2')
        
        # Plot 2: Tension evolution
        stages = ['Thesis', 'Antithesis', 'Synthesis', 'Negation of Negation']
        tensions = [0.8, 0.9, 0.3, 0.5]  # Simulated tension values
        
        ax[1].plot(stages, tensions, 'o-', linewidth=2, markersize=8)
        ax[1].fill_between(stages, tensions, alpha=0.3)
        ax[1].set_ylim(0, 1)
        ax[1].grid(True, alpha=0.3)
        ax[1].set_title('Dialectical Tension Evolution')
        ax[1].set_ylabel('Tension Index')
        ax[1].set_xlabel('Dialectical Stage')
        
        plt.tight_layout()
        plt.savefig('dialectical_process_visualization.png', dpi=150, bbox_inches='tight')
        print("✅ Visualization saved as 'dialectical_process_visualization.png'")
        print("   Left: Vector positions in 2D space")
        print("   Right: Tension evolution through stages")
        
        plt.show()
        
    except ImportError:
        print("⚠️  Matplotlib not available for visualization")
        print("   Install with: pip install matplotlib")

# ============================================================================
# 4. INTERACTIVE EXAMPLES
# ============================================================================

def interactive_examples():
    """
    Interactive examples for user exploration
    """
    print("\n" + "="*70)
    print("4. INTERACTIVE EXAMPLES")
    print("="*70)
    
    print("\n🎮 Try these interactive thought experiments:")
    
    examples = [
        {
            "name": "Moral Dilemma",
            "description": "Should you tell a painful truth or a comforting lie?",
            "thesis": [0.8, 0.2],  # [honesty, compassion]
            "antithesis": [0.2, 0.8]
        },
        {
            "name": "Career Choice",
            "description": "Choose between passion and stability",
            "thesis": [0.9, 0.3],  # [passion, stability]
            "antithesis": [0.3, 0.9]
        },
        {
            "name": "Environmental Policy",
            "description": "Balance economic growth and environmental protection",
            "thesis": [0.7, 0.4],  # [growth, protection]
            "antithesis": [0.4, 0.8]
        },
        {
            "name": "Education Approach",
            "description": "Traditional vs progressive teaching methods",
            "thesis": [0.8, 0.3],  # [tradition, innovation]
            "antithesis": [0.3, 0.9]
        }
    ]
    
    for i, example in enumerate(examples, 1):
        print(f"\n{i}. {example['name']}")
        print(f"   {example['description']}")
        print(f"   Thesis: {example['thesis']}")
        print(f"   Antithesis: {example['antithesis']}")
        
        # Calculate simple synthesis
        synthesis = [(t + a) / 2 for t, a in zip(example['thesis'], example['antithesis'])]
        print(f"   Potential synthesis: {[round(v, 2) for v in synthesis]}")
    
    print("\n🤔 Exercise: For each example, consider:")
    print("   1. What are the strengths of each position?")
    print("   2. What synthesis might emerge?")
    print("   3. How would the negation of negation transform this?")

# ============================================================================
# 5. EDUCATIONAL EXERCISES
# ============================================================================

def educational_exercises():
    """
    Educational exercises for learning dialectics
    """
    print("\n" + "="*70)
    print("5. EDUCATIONAL EXERCISES")
    print("="*70)
    
    print("\n🧠 Exercise 1: Identify Thesis-Antithesis Pairs")
    print("-"*50)
    print("For each concept, identify its dialectical opposite:")
    
    concepts = [
        "Freedom",
        "Equality", 
        "Tradition",
        "Progress",
        "Individualism",
        "Collectivism"
    ]
    
    for concept in concepts:
        print(f"   {concept} ↔ __________")
    
    print("\n🧠 Exercise 2: Imagine Syntheses")
    print("-"*50)
    print("For these oppositions, imagine a synthesis:")
    
    oppositions = [
        ("Central planning", "Free market"),
        ("Absolute truth", "Relativism"),
        ("Nature", "Nurture"),
        ("Science", "Art")
    ]
    
    for thesis, antithesis in oppositions:
        print(f"   {thesis} + {antithesis} → __________")
    
    print("\n🧠 Exercise 3: Apply to Real Situations")
    print("-"*50)
    print("Think of a real conflict or debate you've experienced.")
    print("Apply dialectical analysis:")
    print("   1. What was the thesis (initial position)?")
    print("   2. What was the antithesis (opposing position)?")
    print("   3. Was there a synthesis? If so, what was it?")
    print("   4. What might the negation of negation look like?")
    
    print("\n🧠 Exercise 4: Mathematical Practice")
    print("-"*50)
    print("Given vector v = [1, 2, 3], calculate:")
    print("   1. I(v) = __________")
    print("   2. N(v) = __________")
    print("   3. R(v) = __________")
    print("   4. C(v) = __________")
    print("   5. Verify N(R(v)) = R(N(v)) = C(v)")
    print("   6. Verify N(N(v)) = I(v)")

# ============================================================================
# 6. COMPLETE WORKED EXAMPLE
# ============================================================================

def complete_worked_example():
    """
    Complete worked example of a dialectical process
    """
    print("\n" + "="*70)
    print("6. COMPLETE WORKED EXAMPLE")
    print("="*70)
    
    print("\n📖 Scenario: University Curriculum Reform")
    print("-"*50)
    
    # Define positions
    traditional_position = {
        'name': 'Traditional Curriculum',
        'values': [0.9, 0.8, 0.7, 0.3],  # [depth, structure, tradition, flexibility]
        'description': 'Emphasizes depth, structure, and established knowledge'
    }
    
    progressive_position = {
        'name': 'Progressive Curriculum',
        'values': [0.4, 0.3, 0.2, 0.9],  # [depth, structure, tradition, flexibility]
        'description': 'Emphasizes flexibility, interdisciplinary, and innovation'
    }
    
    print(f"\nThesis: {traditional_position['name']}")
    print(f"Values: Depth={traditional_position['values'][0]}, "
          f"Structure={traditional_position['values'][1]}, "
          f"Tradition={traditional_position['values'][2]}, "
          f"Flexibility={traditional_position['values'][3]}")
    print(f"Description: {traditional_position['description']}")
    
    print(f"\nAntithesis: {progressive_position['name']}")
    print(f"Values: Depth={progressive_position['values'][0]}, "
          f"Structure={progressive_position['values'][1]}, "
          f"Tradition={progressive_position['values'][2]}, "
          f"Flexibility={progressive_position['values'][3]}")
    print(f"Description: {progressive_position['description']}")
    
    # Calculate synthesis using different methods
    print("\n🔬 Calculating synthesis...")
    
    # Method 1: Simple average (standard synthesis)
    standard_synth = [
        (t + p) / 2 
        for t, p in zip(traditional_position['values'], progressive_position['values'])
    ]
    
    print(f"\nStandard synthesis (average):")
    print(f"  Depth: {standard_synth[0]:.2f}")
    print(f"  Structure: {standard_synth[1]:.2f}")
    print(f"  Tradition: {standard_synth[2]:.2f}")
    print(f"  Flexibility: {standard_synth[3]:.2f}")
    print("  → Balanced curriculum with moderate values")
    
    # Method 2: Emphasize common ground (geometric mean)
    geometric_synth = []
    for t, p in zip(traditional_position['values'], progressive_position['values']):
        if t * p > 0:  # Same sign
            geometric_synth.append(np.sqrt(abs(t * p)) * (1 if t >= 0 else -1))
        else:
            geometric_synth.append(0.0)
    
    print(f"\nGeometric synthesis (common ground):")
    print(f"  Depth: {geometric_synth[0]:.2f}")
    print(f"  Structure: {geometric_synth[1]:.2f}")
    print(f"  Tradition: {geometric_synth[2]:.2f}")
    print(f"  Flexibility: {geometric_synth[3]:.2f}")
    print("  → Emphasizes areas of agreement")
    
    # Method 3: Transform then blend (dialectical)
    transformed_traditional = list(reversed(traditional_position['values']))  # Apply R
    transformed_traditional = [-v for v in transformed_traditional]  # Apply N (gives C)
    
    dialectical_synth = [
        0.5 * tt + 0.5 * p
        for tt, p in zip(transformed_traditional, progressive_position['values'])
    ]
    
    print(f"\nDialectical synthesis (INRC transformed):")
    print(f"  Depth: {dialectical_synth[0]:.2f}")
    print(f"  Structure: {dialectical_synth[1]:.2f}")
    print(f"  Tradition: {dialectical_synth[2]:.2f}")
    print(f"  Flexibility: {dialectical_synth[3]:.2f}")
    print("  → Traditional values transformed then blended")
    
    # Negation of negation
    print("\n🌀 Negation of Negation (new thesis emerges):")
    print("The synthesis becomes a new thesis for further development")
    print("Example: 'Integrated Curriculum' that:")
    print("  • Maintains core disciplinary depth")
    print("  • Uses modular, flexible structure")
    print("  • Respects tradition while innovating")
    print("  • Balances structure with student choice")
    
    # Tension analysis
    print("\n📊 Tension Analysis:")
    differences = [abs(t - p) for t, p in zip(
        traditional_position['values'], progressive_position['values']
    )]
    tension_index = sum(differences) / (sum(traditional_position['values']) + 
                                       sum(progressive_position['values']))
    
    print(f"  Maximum difference: {max(differences):.2f} (Flexibility)")
    print(f"  Minimum difference: {min(differences):.2f} (Depth)")
    print(f"  Overall tension: {tension_index:.2f}")
    print(f"  → {'High' if tension_index > 0.6 else 'Moderate' if tension_index > 0.3 else 'Low'} dialectical tension")

# ============================================================================
# MAIN EXECUTION
# ============================================================================

def main():
    """
    Main function to run all examples
    """
    print("\n" + "="*80)
    print("XENOPOULOS FOURTH LOGICAL STRUCTURE - BASIC EXAMPLES")
    print("="*80)
    print("\nEducational examples demonstrating Hegelian dialectics with INRC operators")
    print("Based on Epameinondas Xenopoulos' mathematical formalization")
    
    # Run all demonstrations
    demonstrate_basic_concepts()
    demonstrate_simple_dialectics()
    visualize_dialectical_process()
    interactive_examples()
    educational_exercises()
    complete_worked_example()
    
    print("\n" + "="*80)
    print("SUMMARY & KEY INSIGHTS")
    print("="*80)
    
    print("\n🎯 Key Concepts Demonstrated:")
    print("   1. Thesis-Antithesis-Synthesis cycle")
    print("   2. INRC operators forming Klein-4 group")
    print("   3. Mathematical correction: order reversal vs cyclic permutation")
    print("   4. Multiple synthesis methods")
    print("   5. Tension analysis and evolution")
    
    print("\n🔧 How to Use This Framework:")
    print("   1. Define positions as vectors")
    print("   2. Apply INRC operators for transformations")
    print("   3. Calculate synthesis using appropriate method")
    print("   4. Analyze tension and evolution")
    print("   5. Iterate through dialectical cycles")
    
    print("\n📚 Further Learning:")
    print("   • Run: python examples/advanced_dialectics.py")
    print("   • Explore: tests/test_klein4_group.py")
    print("   • Study: Xenopoulos' original papers")
    print("   • Apply: To your own conflicts or debates")
    
    print("\n✅ Basic examples completed successfully!")
    print("   You now understand the core concepts of Xenopoulos' dialectical framework.")

if __name__ == "__main__":
    # Handle command line arguments
    import argparse
    
    parser = argparse.ArgumentParser(
        description="Basic examples of Xenopoulos' Fourth Logical Structure"
    )
    parser.add_argument(
        '--section',
        type=str,
        choices=['concepts', 'processes', 'visual', 'interactive', 'exercises', 'complete', 'all'],
        default='all',
        help='Which section to run'
    )
    
    args = parser.parse_args()
    
    if args.section == 'concepts' or args.section == 'all':
        demonstrate_basic_concepts()
    if args.section == 'processes' or args.section == 'all':
        demonstrate_simple_dialectics()
    if args.section == 'visual' or args.section == 'all':
        visualize_dialectical_process()
    if args.section == 'interactive' or args.section == 'all':
        interactive_examples()
    if args.section == 'exercises' or args.section == 'all':
        educational_exercises()
    if args.section == 'complete' or args.section == 'all':
        complete_worked_example()
    
    if args.section == 'all':
        print("\n✅ All basic examples completed!")
    else:
        print(f"\n✅ Section '{args.section}' examples completed!")